language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -y update
    - sudo apt-get -qq install valgrind libboost-regex-dev g++-4.8
    - phpenv rehash
    - ulimit -c unlimited || true

install:
    - cd ext
    - phpize
    - CXX=g++-4.8 CXXFLAGS=-std=c++11 ./configure --enable-routeman
    - make
    - make install
    - echo "extension=routeman.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
    - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes phpunit
